services:
  weather.command:
    class: Domain\Weather\Command\WeatherCommand
    arguments:
      - '@weather.repo'
      - '@weather.temp.repo'
      - '@weather.parser'
      - '%city%'
    tags:
      - { name: console.command }