services:
  Controller\AbstractController:
    public: true
    calls:
      - [setRequest, ['@request_stack']]

  Controller\WeatherController:
    arguments:
      - '@weather.model'
    parent: Controller\AbstractController